version: '3'

services:
  django:
    build: 
      context: './'
      dockerfile: Dockerfile.prod
    entrypoint: /django/entrypoint.prod.sh
    env_file:
      - env/.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - env/.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - django

volumes:
  pg-data:
  static_volume:
  media_volume: