version: '3'

services:
  web:
    build: 
      context: './project'
      dockerfile: Dockerfile.prod
    container_name: 'drf-template_web'
    command: gunicorn config.wsgi:application -c config/gunicorn.conf.py --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    depends_on:
      - web

volumes:
  pg-data:
  static_volume:
  media_volume: